# # -*- coding: utf-8 -*-
# """Anxiety user

# Automatically generated by Colaboratory.

# Original file is located at
#     https://colab.research.google.com/drive/1DRiKnaxkqfInB78gUUayq3Lq1g6NTwUp
# """

# import pandas as pd
# import numpy as np
# import warnings
# from sklearn.ensemble import GradientBoostingClassifier

# !pip install --upgrade scikit-learn

# import sklearn
# print(sklearn.__version__)

# df = pd.read_csv("/content/Anxiety.csv")
# df.info()

# my_dict = {0 :'How often do you experience a sense of restlessness or feeling on edge?',
#            1 :'Do you find yourself worrying about various aspects of your life, even when there is no immediate cause for concern?',
#            2 :'In social situations, how often do you feel nervous or apprehensive?',
#            3 : 'How frequently do you have difficulty controlling racing thoughts or intrusive worries?',
#            4 : 'Do you often experience physical symptoms of anxiety, such as trembling, sweating, or a racing heart?',
#            5 : 'On a regular basis, how often do you find it challenging to relax or calm your mind?',
#            6 : 'When faced with uncertainties or changes, how often do you feel a heightened level of anxiety?'}

# X = df.drop('A_severity', axis=1)
# y = df['A_severity']

# gb_classifier = GradientBoostingClassifier(learning_rate = 0.01, max_depth = 3, n_estimators = 50)
# gb_classifier.fit(X, y)

# user_input = []
# for x in my_dict:
#   print(my_dict[x])
#   temp = int(input())
#   user_input.append(temp)

# add_val = sum(user_input)
# user_input.append(add_val)
# user_input.append(add_val*2)

# user_input = np.array([user_input])
# user_df = pd.DataFrame(user_input)

# predicted_gb = gb_classifier.predict(user_df)

# print(f"The predicted result is: {predicted_gb[0]}")
# warnings.filterwarnings('ignore',  message="X does not have valid feature names,*")

# import pickle

# from google.colab import drive
# drive.mount('/content/drive')

# filename='Anxiety_model.sav'
# pickle.dump(gb_classifier,open(filename,'wb'))

# loaded_model=pickle.load(open('Anxiety_model.sav','rb'))


import pandas as pd
import numpy as np
from sklearn.ensemble import GradientBoostingClassifier
# Load the dataset
df = pd.read_csv("Anxiety.csv")

# Model training
X = df.drop('A_severity', axis=1)
y = df['A_severity']

gb_classifier = GradientBoostingClassifier(learning_rate=0.01, max_depth=3, n_estimators=50)
gb_classifier.fit(X, y)

# Function to get questions with options
def get_questionsa():
    my_dicta={'a':'How often do you experience a sense of restlessness or feeling on edge?',
           'b' :'Do you find yourself worrying about various aspects of your life, even when there is no immediate cause for concern?',
           'c' :'In social situations, how often do you feel nervous or apprehensive?',
           'd' : 'How frequently do you have difficulty controlling racing thoughts or intrusive worries?',
           'e' : 'Do you often experience physical symptoms of anxiety, such as trembling, sweating, or a racing heart?',
           'f' : 'On a regular basis, how often do you find it challenging to relax or calm your mind?',
           'g' : 'When faced with uncertainties or changes, how often do you feel a heightened level of anxiety?',
           'aa':{'0':'Never','1':'Sometimes','2':'Often','3':'Always'}
           }



    return {'questionsa': my_dicta}

# Function to make predictions
def predicta(user_responsesa):
    add_val = sum(user_responsesa)
    user_responsesa.append(add_val)
    user_responsesa.append(add_val * 2)

    user_input = np.array([user_responsesa])
    user_df = pd.DataFrame(user_input)

    predicted_gb = gb_classifier.predict(user_df)

    return {'result': str(predicted_gb[0])}

